version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8080}:80
    environment:
      UPSTREAMS: proxy:3000
    networks:
      - backend
    depends_on:
      - proxy

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.build
    environment:
      PORT: 3000
      MAX_PARALLEL_REQUESTS: ${PORT:-1}
      MAX_CONNECTIONS: ${PORT:-10}
      REDIS_DATABASE: ${PORT:-0}
      REDIS_HOST: ${PORT:-redis}
      REDIS_PORT: ${PORT:-6379}
      CACHE_CAPACITY: ${PORT:-100}
      CACHE_TTL: ${PORT:-10000}
    networks:
      - backend
    depends_on:
      - redis
    ports:
      - 8081:3000

  redis:
    image: redis:5
    volumes:
      - "redis-data:/data"
    ports:
      - 6379:6379
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
